### ISSUE TITLE
ep, ne and rb scores are lacking

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#1]
We need to calculate `ep`, `ne` and `rb` for each node in the tree. I know that @huddlej has a clean way to do this well. I don't know whether this is better as `augur scores` or `augur sequence-traits` or if it's better as a separate script in `seasonal-flu/scripts/`.

**Comment by rneher** [comment]
I don't see a need for this outside of flu right now. So my suggestion would be to develop a clean and generic way in flu that can be moved to `augur` at a later point if need arises.

**Comment by huddlej** [comment]
There are two possible reasons I'd want to include this in augur. Even though those specific attributes are flu-specific, the way they are calculated is pathogen-independent. Placing this code in augur would also avoid duplication of code between my other flu repo and the seasonal flu repo.

**Comment by huddlej** [comment]
This is somewhat addressed by 8df9cf3, but we still need a non-epitope mask for NA (bhatt_nonepitope, perhaps) and a way of optionally displaying RBS mutations for just HA and not NA in auspice (there might already be a way of doing this that I'm not aware of).
