### ISSUE TITLE
Missing description (in auspice footer)

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/seasonal-flu#182]
The [description.md](https://github.com/nextstrain/seasonal-flu/blob/master/config/description.md) isn't appearing in [the live seasonal-flu/h3n2/ha/2y](https://next.nextstrain.org/seasonal-flu/h3n2/ha/2y), instead we're getting the hardcoded auspice description: 

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/3641dfe9-56f7-47f0-8785-05f9704feb2d">

Similarly for other subtypes / segments / resolutions

**Comment by joverlee521** [comment]
Thanks for flagging @jameshadfield! 

Datasets uploaded on 2023-03-23 (https://next.nextstrain.org/seasonal-flu/h3n2/ha/2y@2023-03-23) still included the custom description. The datasets uploaded the following week on 2023-03-31 (https://next.nextstrain.org/seasonal-flu/h3n2/ha/2y@2023-04-01) no longer has the description. 

The date coincides with the merge of the major [refactoring PR](https://github.com/nextstrain/seasonal-flu/pull/76), so we must have missed this change.
