### ISSUE TITLE
report.smk: Migrate to Nextclade v3

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/seasonal-flu#187]
[Migration to Nextclade v3 guide](https://docs.nextstrain.org/projects/nextclade/en/stable/user/migration-v3.html) for reference.

The core workflow was migrated to Nextclade v3 in https://github.com/nextstrain/seasonal-flu/pull/145. 

## TODOs

- [ ] update nextclade2 commands in [report.smk](https://github.com/nextstrain/seasonal-flu/blob/3b7ce7a17de7aff8261aba5d008becbcd78ac47a/workflow/snakemake_rules/report.smk)

**Comment by joverlee521** [comment]
@huddlej do you still use the report.smk rules? Can we just remove the rules file entirely?

**Comment by huddlej** [comment]
@joverlee521 I think it's safe to remove that report file, since we estimate clade frequencies from Nextclade outputs with a different method now. I'll push a PR to remove this.
