### ISSUE TITLE
LBI is lacking

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#2]
We should have `lbi` calculated for all nodes in the tree. I suspect this should just be a simple script in `scripts/`.

**Comment by rneher** [comment]
in terms of tree annotations, we could split it into sequence based ones (`ep` etc), metadata based ones (`age`, `vaccine`, etc) and tree based ones like `lbi` and `fitness`. But any of these are best as flu specific scripts in `scripts/`

**Comment by jameshadfield** [comment]
I'd propose making this an augur command as it's useful outside of flu builds.

**Comment by huddlej** [comment]
I have an augur-style command for this already. I'll work on a PR to include this in augur.
