### ISSUE TITLE
Substitution model not loading on nextflu/auspice

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#22]
@rneher ---

I don't think I introduced this bug. But you first might want to check one of your existing JSONs to confirm it's present there as well. If I build `flu/who/h3n2/ha/2y/cell/hi`, the substitution model inference of tip antigenic advancement looks good via auspice v2:

<img width="955" alt="screen shot 2019-01-30 at 8 14 10 am" src="https://user-images.githubusercontent.com/1176109/51995172-0a9fff80-2467-11e9-91e5-d2457e4618b1.png">

However, the display in auspice v1 (`nextflu/auspice`) doesn't register these antigenic changes:

<img width="866" alt="screen shot 2019-01-30 at 8 15 24 am" src="https://user-images.githubusercontent.com/1176109/51995252-358a5380-2467-11e9-88bc-03e79258fdfd.png">

I thought this might have been how substitutions are encoded in `flu_who_h3n2_ha_2y_cell_hi_titer-sub-model.json`, but this actually looks good. Thinking now it may be entirely an issue with auspice v1.

**Comment by rneher** [comment]
just saw you already changed that.

**Comment by trvrb** [comment]
Yeah. I did here: https://github.com/blab/nextflu/commit/175b49770a10dbeb51d5b5e39f99415d3c28670c. The file seems to load okay. (No warnings in console)

**Comment by trvrb** [comment]
I just figured this out. We had left out `sequences.json` from https://github.com/nextstrain/seasonal-flu/blob/master/batch.py#L66. Easy fix.
