### ISSUE TITLE
Prioritize rather than filter to "complete" genomes

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#24]
Currently, besides reference genomes, `select_strains.py` is only passing through viruses that possess both HA and NA segments (due to our use of `--segments ha na` in the snakefile). For time pivots back about 3-6 months this is okay and there are usually enough strains with both HA and NA to fill sampling bins. However, some strains are just only getting HA sequenced. This was especially obvious looking just now where there are a number of H3s from January with just HA. These tend to be uploaded by groups that are not CCs.

I would propose to modify `select_strains.py` so that "complete" genome (as in possessing all entries in `--segments`) becomes another factor in `priority` rather than a hard constraint.

**Comment by rneher** [comment]
I would add a `--all-segments` flag to force the hard filtering, otherwise prioritize.
