### ISSUE TITLE
how to plot the following figure?

### ISSUE THREAD

**Issue by lixingguang** [nextstrain/seasonal-flu#27]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/10130954/55139842-ac934e00-5171-11e9-91c7-f6c5e973dbe3.png">

**Comment by barneypotter24** [comment]
Hi @lixingguang,

If you are using Auspice to visualize your trees, there is a utility to download trees as SVG that can be found at the bottom of the in-browser display. Hopefully this helps.

**Comment by lixingguang** [comment]
@barneypotter24 is there any script for plot this kinds of figures, I want to plot my data like this, thanks.
