### ISSUE TITLE
Batched WHO jobs exceed disk limit of AWS instances

### ISSUE THREAD

**Issue by barneypotter24** [nextstrain/seasonal-flu#28]
Submitting this here per conversations on Slack and with Tom.

The latest H3N2 WHO builds failed multiple times when they were run on AWS, seemingly because they exceed the disk limit (22GB) allocated to instances on AWS. They were submitted using:

`python batch.py --system batch --version who`

The logs for the failed run can be found [here](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=nextstrain-job/default/e44c55f5-1c76-4d8c-8e58-9c743353308a). The build seems to fail during the final `zip` step, which points toward an issue with disk space. This will hopefully be helped by https://github.com/nextstrain/augur/pull/278, but as a short term solution can also be helped by subdividing WHO builds by more than just subtype.

**Comment by tsibley** [comment]
Turns out this isn't a disk space issue at all. The zip step completes successfully and the zip file is uploaded to S3. The job exits with failure because snakemake did.

**Comment by tsibley** [comment]
When I download the zip file and extract the Snakemake log, at the end it includes:

```
Finished job 756.
594 of 1024 steps (58%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /nextstrain/build/.snakemake/log/2019-04-22T222630.419557.snakemake.log
```

looking further up, I find:

```
    Error in rule titers_tree:
        jobid: 295
        output: results/titers-tree-model_niid_h3n2_ha_2y_cell_hi.json

RuleException:
CalledProcessError in line 436 of /nextstrain/build/Snakefile_base:
Command ' set -euo pipefail;  
        augur titers tree             --titers data/niid_h3n2_cell_hi_titers.tsv             --tree results/tree_niid_h3n2_ha_2y_cell_hi.nwk             --output results/titers-tree-model_nii
  File "/nextstrain/build/Snakefile_base", line 436, in __rule_titers_tree
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```

**Comment by trvrb** [comment]
As mentioned above, this issue was not a disk issue. It was a missing file issue causing Snakemake to fail. The better specified issue was: https://github.com/nextstrain/augur/issues/279 and the resolution was: https://github.com/nextstrain/augur/pull/281.
