### ISSUE TITLE
Tip frequencies are lacking

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#3]
We need to calculate `tip-frequencies.json` via KDE frequencies in order to restore the frequencies panel. I believe this functionality should be part of `augur frequencies` where `--tree` is passed in. And then maybe have flags for `--method kde` and `--tips-only` or some such.

**Comment by rneher** [comment]
sounds good to me. I haven't touched the KDE part to avoid messing with John's dev. i would make integration easier if the KDE part was sub-classed in a similar way into a part that operates on alignments and trees with an underlying core machinery. @huddlej, probably best if you hash out a proposal for this.

**Comment by huddlej** [comment]
Resolved by #7.
