### ISSUE TITLE
cTiterSub is lacking

### ISSUE THREAD

**Issue by trvrb** [nextstrain/seasonal-flu#4]
Currently `augur titers sub` outputs a JSON that has entries for `avidity`, `potency`, `substitution`, `titers`, but lacks a `nodes` entry that could be used to decorate the final `tree.json` via `augur export`.

This change needs to happen to `augur titers sub` and then the seasonal build can be updated.

**Comment by rneher** [comment]
good point. this raises one other issue. The hope was to have the `titer sub` command be independent of a tree. A `nodes` field in the json  requires a tree. We could either have `tree` as an optional argument or have a separate rule that attached a `subs` model to a tree.

**Comment by huddlej** [comment]
I'd vote for an optional `tree` argument.
