### ISSUE TITLE
[Feature request] Add most recent Northern Hemisphere vaccine strains to builds

### ISSUE THREAD

**Issue by huddlej** [nextstrain/seasonal-flu#49]
**Context**  
The [most recent vaccine strains for the upcoming Northern Hemisphere season](https://www.who.int/influenza/vaccines/virus/recommendations/2020-21_north/en/) aren't included in live builds.

**Description**   

These strains need to be added to the vaccines JSON and references files for H3N2 and H1N1pdm.

**Comment by joverlee521** [comment]
Added in latest commit: https://github.com/nextstrain/seasonal-flu/commit/3a5b6192af0eab6909216dfc3e13c585090bd239
