### ISSUE TITLE
The json files exported by augur can not be visualized by the auspice

### ISSUE THREAD

**Issue by sunshine1126** [nextstrain/seasonal-flu#51]
Hello, the command `nextstrain view `./auspice/` can not view the json file. Can you help me address these problems? 
![image](https://user-images.githubusercontent.com/32659317/82033523-6d0a2700-96cf-11ea-84fe-8cc973520862.png)

**Comment by tsibley** [comment]
Hi @sunshine1126! The output here from `nextstrain view` is a small bug (https://github.com/nextstrain/cli/issues/60) and its warning about "No datasets detected" is misleading. :-/ I've haven't had a chance to fix it yet, so I'm sorry that it's tripped you up! If you browse to `http://127.0.0.1:4000` anyway, you should see the datasets.

**Comment by sunshine1126** [comment]
@tsibley Thanks for your reply and I will try to address the problems according to your suggestions.

**Comment by sunshine1126** [comment]
I have addressed this problem@tsibley and thanks.
