### ISSUE TITLE
Annotate new clades for H3N2 and H1N1pdm

### ISSUE THREAD

**Issue by huddlej** [nextstrain/seasonal-flu#52]
**Context**  
H3N2 has an emerging clade from A1b/135K that has reached high enough frequency to start tracking. We agreed to name this clade A1b/186D and annotate based on its 135K, 186D, and 190N.

H1N1pdm has several previously identified clades that we haven't annotated yet. These include:

  - 5A: 129D and 185I
  - 5B: 160M

And a newer clade:

  - 187A/189E

**Description**   
We need to add annotations for these new clades to the corresponding clades TSV files in the builds and confirm visually that they work as expected.

**Comment by joverlee521** [comment]
Did we decided on a name for the newer clade in H1N1 for 187A/189E?

**Comment by huddlej** [comment]
I don't think we decided. It could be "[6b1.A/187A](https://nextstrain.org/staging/flu/seasonal/h1n1pdm/ha/2y?c=gt-HA1_187)" or "[6b1.A/189E](https://nextstrain.org/staging/flu/seasonal/h1n1pdm/ha/2y?c=gt-HA1_189)".

@trvrb @rneher Do you have any preference?

**Comment by huddlej** [comment]
From the call this morning, we decided to annotate:

  - "6b1.A/187A" based on the 187A and 189E mutations
  - "6b1.A/156K" based on 156K and 161I

We didn't discuss the 161I mutation for the 156K clade, but as Richard pointed out in Slack this mutation is present on the same branch with the 156K mutation and also helps distinguish this clade from older clades that carry the 156K.
