### ISSUE TITLE
Estimate tip frequencies up to the month of latest available strains

### ISSUE THREAD

**Issue by huddlej** [nextstrain/seasonal-flu#54]
We currently estimate tip frequencies up to the current date of a given build, but the latest available sequences are often collected one or two months prior to the current date. As a result, the frequencies misrepresent what we know about the present. For H3N2, this lack of data also makes the forecasts less reliable because they end up being 14-15 month forecasts instead of 12-month forecasts.

Instead of using the current date as the max date for tip frequencies, we should dynamically determine the max date from the available sequences in the analysis, rounding up to the first day of the next month. For example, if the latest available sequence is from April 15, we would set the max date to May 1.

**Comment by genehack** [comment]
@huddlej This seems like it would be a pretty easy change, right? Sort the metadata by date, get the newest one, round up the month, and then pass that into the tip frequency calculation? Is this still something you think is worth doing?

**Comment by huddlej** [comment]
We actually already addressed this issue by [adding support for a max date for frequencies](https://github.com/nextstrain/seasonal-flu/commit/5591eba99d8e5c550440c1b8f602fcfe5b308c65) and [setting the max date to 4 weeks ago for our private flu builds](https://github.com/nextstrain/seasonal-flu/blob/f4a19b2a02c221058f90a1f1bfd14b887e036fb5/profiles/nextflu-private.yaml#L39).

The broader issue of representing uncertainty of recent frequencies is also addressed by [the flu_frequencies workflow](https://github.com/nextstrain/flu_frequencies) we use in reports.
