### ISSUE TITLE
Color strains by database submission date

### ISSUE THREAD

**Issue by huddlej** [nextstrain/seasonal-flu#55]
Strain submission to GISAID and other databases often lags by one to two months from the actual collection date. When we make new seasonal flu builds, it would be helpful to identify which strains were recently added to the database.

The [ncov builds address this problem by adding a "recency" color-by attribute](https://github.com/nextstrain/ncov/blob/22c435106b39f6b644ee9b80208752a9612436e8/workflow/snakemake_rules/main_workflow.smk#L750-L764). This [categorical attribute bins submission dates into useful groups for ncov analysis](https://nextstrain.org/ncov/global?c=recency).

For flu, a similar categorical attribute that highlights sequences submitted in the last month or before should be sufficient.

**Comment by rneher** [comment]
I'd think 
 * last week
 * last month
 * last quarter
 * older
would be enough.
