### ISSUE TITLE
CDS coordinates are incorrect for Vic and Yam hemagglutinin

### ISSUE THREAD

**Issue by huddlej** [nextstrain/seasonal-flu#57]
**Current Behavior**  

@kistlerk noticed that the demarcated region for HA1 is not divisible by 3 in the HA reference files for [Vic](https://github.com/nextstrain/seasonal-flu/blob/36a73af3ba09a636e2656f636615f42846b7e638/config/reference_vic_ha.gb#L40-L48) and [Yam](https://github.com/nextstrain/seasonal-flu/blob/36a73af3ba09a636e2656f636615f42846b7e638/config/reference_yam_ha.gb#L41-L49).

**Expected behavior**  

The CDS for HA1 should say 57..1094 rather than 1095 and SigPep should be 12..56.

CDS coordinates in GenBank format are 1-based and closed. To calculate the amino acids in a given range, you have to add 1 to the range before dividing by 3. For [H3N2's HA](https://github.com/nextstrain/seasonal-flu/blob/6bb288f5e1c7dda077997920aff3bbacfef65782/config/reference_h3n2_ha.gb#L48-L56), we get the 16 amino acids of SigPep by (48 - 1 + 1) / 3 and the 329 of HA1 with (1035 - 49 + 1) / 3.

**Comment by joverlee521** [comment]
From [Slack conversation](https://bedfordlab.slack.com/archives/CBVHPFMGX/p1707930965495499?thread_ts=1707927501.556419&cid=CBVHPFMGX), [coordinates for Vic was fixed](https://github.com/nextstrain/seasonal-flu/commit/236ae409745d3d44e14f4d1a920e669bcc234672) but not Yam (yet).
