### ISSUE TITLE
Minor typo in README: "depending on the assay that passage history of the antigens"?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/seasonal-flu#77]
I think there's a minor typo in the README:

> These antigenic data come in four flavors depending on the assay that passage history of the antigens.

Should possibly be: "assay _and_ passage history"

**Comment by genehack** [comment]
It seems like the README has been rewritten, and the phrase mentioned in this issue no longer exists — the word "flavors" doesn't appear anywhere in this repo with the exception of this issue. 

Closing this out.
